# Generated by Django 4.1.5 on 2023-01-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('road_address', models.TextField()),
                ('phone_number', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField()),
                ('img_url', models.TextField()),
                ('comment', models.TextField()),
                ('restaurant_type', models.TextField()),
                ('vectors', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('hate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_data_seq', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.IntegerField()),
                ('user_id', models.TextField()),
                ('name', models.TextField()),
                ('road_address', models.TextField()),
                ('phone_number', models.TextField()),
                ('img_url', models.TextField()),
                ('comment', models.TextField()),
                ('restaurant_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
