# Generated by Django 4.1.5 on 2023-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_feed_vectors_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='comment',
            field=models.TextField(null='-'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='phone_number',
            field=models.TextField(null='000-0000-0000'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='restaurant_type',
            field=models.TextField(null='-'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='vectors',
            field=models.TextField(null='[]'),
        ),
    ]
