# Generated by Django 4.1.5 on 2023-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_feed_comment_alter_feed_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagLog',
            fields=[
                ('user_data_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('name', models.TextField()),
                ('road_address', models.TextField()),
                ('tag_name', models.TextField()),
                ('confidence', models.FloatField()),
                ('preference', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
