# Generated by Django 4.1.5 on 2023-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_usertaglog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaglog',
            old_name='user_data_seq',
            new_name='user_log_seq',
        ),
    ]
