# Generated by Django 4.1.5 on 2023-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_bookmark_hate_like_reply_usersearchlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='feed_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='hate',
            old_name='feed_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='feed_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='feed_id',
            new_name='restaurant_id',
        ),
    ]
